//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COVID19_Part2_WebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Covid_19_PackingEntities : DbContext
    {
        public Covid_19_PackingEntities()
            : base("name=Covid_19_PackingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<DeliveryDetail> DeliveryDetails { get; set; }
        public virtual DbSet<DistributionCentre> DistributionCentres { get; set; }
        public virtual DbSet<HomeDelivery> HomeDeliveries { get; set; }
        public virtual DbSet<LoginRole> LoginRoles { get; set; }
        public virtual DbSet<LoginUserRole> LoginUserRoles { get; set; }
        public virtual DbSet<LoginUser> LoginUsers { get; set; }
        public virtual DbSet<PackingCentre> PackingCentres { get; set; }
        public virtual DbSet<PackingDetail> PackingDetails { get; set; }
        public virtual DbSet<StatusPriority> StatusPriorities { get; set; }
    }
}
