//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COVID19_Part2_WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDetail
    {
        public int ID { get; set; }
        public int DeliveryID { get; set; }
        public bool DestinationIsHome { get; set; }
        public int DestinationID { get; set; }
        public int DestinationIndex { get; set; }
        public System.DateTime DestinationStart { get; set; }
        public System.DateTime DestinationEnd { get; set; }
        public System.DateTime ActualStart { get; set; }
        public System.DateTime ActualEnd { get; set; }
    
        public virtual Delivery Delivery { get; set; }
    }
}
