//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COVID19_Part2_WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoginUser()
        {
            this.Deliveries = new HashSet<Delivery>();
            this.DistributionCentres = new HashSet<DistributionCentre>();
            this.DistributionCentres1 = new HashSet<DistributionCentre>();
            this.HomeDeliveries = new HashSet<HomeDelivery>();
            this.HomeDeliveries1 = new HashSet<HomeDelivery>();
            this.LoginUserRoles = new HashSet<LoginUserRole>();
            this.PackingCentres = new HashSet<PackingCentre>();
        }
    
        public int ID { get; set; }
        public string LoginID { get; set; }
        public byte[] LoginPassword { get; set; }
        public string FullName { get; set; }
        public System.DateTime LastLogin { get; set; }
        public byte LoginFail { get; set; }
        public bool AccountIsLocked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Deliveries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributionCentre> DistributionCentres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributionCentre> DistributionCentres1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeDelivery> HomeDeliveries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeDelivery> HomeDeliveries1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginUserRole> LoginUserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackingCentre> PackingCentres { get; set; }
    }
}
